### ISSUE TITLE
`isPreChatFormEnabled` isn't working

### ISSUE THREAD

**Issue by haohaowasky** [emostar/flutter-zendesk#33]
Version: 2.0.0

Hi there, 

I was trying to use `setVisitorInfo` method to pre set visitor info and `isPreChatFormEnabled = False` method to get rid of the auto questionaries. 

But seems like none of these two are working. The chat bot still asks me the name phonenumber and email. 

Would you advice how to address ?

**Comment by emren** [comment]
Hi, we had the same problem, solved it with using below code at yaml
```
zendesk:
    git:
      url: https://github.com/rafay-tariq/flutter-zendesk
      ref: patch-3
```
